### ISSUE TITLE
Error in swagger-ui because of latest changes in yiisoft/view

### ISSUE THREAD

**Issue by tarunjangra** [yiisoft/view#156]
### What steps will reproduce the problem?
I upgraded my packages with `composer update`. It upgraded `yiisoft/view` to hash `2d8d972`. It broke swagger ui for me in `app-api` project.

### What is the expected result?
It should show swagger ui.

### What do you get instead?
```
TypeError: call_user_func_array(): Argument #1 ($function) must be a valid callback, class Yiisoft\View\WebView does not have a method "withDefaultParameters" in /app/vendor/yiisoft/factory/src/Definition/ArrayDefinitionBuilder.php:67
Stack trace:
#0 /app/vendor/yiisoft/factory/src/Definition/ArrayDefinition.php(129): Yiisoft\Factory\Definition\ArrayDefinitionBuilder->build(Object(Yiisoft\Di\Container), Object(Yiisoft\Factory\Definition\ArrayDefinition))
#1 /app/vendor/yiisoft/di/src/Container.php(371): Yiisoft\Factory\Definition\ArrayDefinition->resolve(Object(Yiisoft\Di\Container))
#2 /app/vendor/yiisoft/di/src/Container.php(319): Yiisoft\Di\Container->buildInternal('Yiisoft\\View\\We...')
#3 /app/vendor/yiisoft/di/src/Container.php(145): Yiisoft\Di\Container->build('Yiisoft\\View\\We...')
#4 /app/vendor/yiisoft/factory/src/Definition/ClassDefinition.php(46): Yiisoft\Di\Container->get('Yiisoft\\View\\We...')
#5 /app/vendor/yiisoft/factory/src/Definition/DefinitionResolver.php(55): Yiisoft\Factory\Definition\ClassDefinition->resolve(Object(Yiisoft\Di\Container))
#6 /app/vendor/yiisoft/factory/src/Definition/DefinitionResolver.php(38): Yiisoft\Factory\Definition\DefinitionResolver::resolve(Object(Yiisoft\Di\Container), Object(Yiisoft\Factory\Definition\ClassDefinition))
#7 /app/vendor/yiisoft/factory/src/Definition/ArrayDefinitionBuilder.php(54): Yiisoft\Factory\Definition\DefinitionResolver::resolveArray(Object(Yiisoft\Di\Container), Array)
#8 /app/vendor/yiisoft/factory/src/Definition/ArrayDefinition.php(129): Yiisoft\Factory\Definition\ArrayDefinitionBuilder->build(Object(Yiisoft\Di\Container), Object(Yiisoft\Factory\Definition\ArrayDefinition))
#9 /app/vendor/yiisoft/di/src/Container.php(371): Yiisoft\Factory\Definition\ArrayDefinition->resolve(Object(Yiisoft\Di\Container))
#10 /app/vendor/yiisoft/di/src/Container.php(319): Yiisoft\Di\Container->buildInternal('Yiisoft\\Yii\\Vie...')
#11 /app/vendor/yiisoft/di/src/Container.php(145): Yiisoft\Di\Container->build('Yiisoft\\Yii\\Vie...')
#12 /app/vendor/yiisoft/factory/src/Definition/ClassDefinition.php(46): Yiisoft\Di\Container->get('Yiisoft\\Yii\\Vie...')
#13 /app/vendor/yiisoft/factory/src/Definition/DefinitionResolver.php(55): Yiisoft\Factory\Definition\ClassDefinition->resolve(Object(Yiisoft\Di\Container))
#14 /app/vendor/yiisoft/factory/src/Definition/DefinitionResolver.php(38): Yiisoft\Factory\Definition\DefinitionResolver::resolve(Object(Yiisoft\Di\Container), Object(Yiisoft\Factory\Definition\ClassDefinition))
#15 /app/vendor/yiisoft/factory/src/Definition/ArrayDefinitionBuilder.php(54): Yiisoft\Factory\Definition\DefinitionResolver::resolveArray(Object(Yiisoft\Di\Container), Array)
#16 /app/vendor/yiisoft/factory/src/Definition/ArrayDefinition.php(129): Yiisoft\Factory\Definition\ArrayDefinitionBuilder->build(Object(Yiisoft\Di\Container), Object(Yiisoft\Factory\Definition\ArrayDefinition))
#17 /app/vendor/yiisoft/di/src/Container.php(387): Yiisoft\Factory\Definition\ArrayDefinition->resolve(Object(Yiisoft\Di\Container))
#18 /app/vendor/yiisoft/di/src/Container.php(366): Yiisoft\Di\Container->buildPrimitive('Yiisoft\\Swagger...')
#19 /app/vendor/yiisoft/di/src/Container.php(319): Yiisoft\Di\Container->buildInternal('Yiisoft\\Swagger...')
#20 /app/vendor/yiisoft/di/src/Container.php(145): Yiisoft\Di\Container->build('Yiisoft\\Swagger...')
#21 /app/vendor/yiisoft/injector/src/Injector.php(267): Yiisoft\Di\Container->get('Yiisoft\\Swagger...')
#22 /app/vendor/yiisoft/injector/src/Injector.php(248): Yiisoft\Injector\Injector->resolveObjectParameter(Object(Yiisoft\Injector\ResolvingState), 'Yiisoft\\Swagger...', false)
#23 /app/vendor/yiisoft/injector/src/Injector.php(199): Yiisoft\Injector\Injector->resolveNamedType(Object(Yiisoft\Injector\ResolvingState), Object(ReflectionNamedType), false)
#24 /app/vendor/yiisoft/injector/src/Injector.php(150): Yiisoft\Injector\Injector->resolveParameter(Object(ReflectionParameter), Object(Yiisoft\Injector\ResolvingState))
#25 /app/vendor/yiisoft/injector/src/Injector.php(66): Yiisoft\Injector\Injector->resolveDependencies(Object(ReflectionFunction), Array)
#26 /app/vendor/yiisoft/request-model/src/CallableWrapper.php(40): Yiisoft\Injector\Injector->invoke(Object(Closure), Array)
#27 /app/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(88): Yiisoft\RequestModel\CallableWrapper->process(Object(HttpSoft\Message\ServerRequest), Object(App\NotFoundHandler))
#28 /app/vendor/yiisoft/data-response/src/Middleware/FormatDataResponse.php(25): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#29 /app/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(88): Yiisoft\DataResponse\Middleware\FormatDataResponse->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#30 /app/src/Middleware/ExceptionMiddleware.php(28): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#31 /app/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(88): App\Middleware\ExceptionMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#32 /app/vendor/yiisoft/data-response/src/Middleware/FormatDataResponse.php(25): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#33 /app/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(88): Yiisoft\DataResponse\Middleware\FormatDataResponse->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#34 /app/vendor/yiisoft/request-body-parser/src/RequestBodyParser.php(130): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#35 /app/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(88): Yiisoft\Request\Body\RequestBodyParser->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#36 /app/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(53): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#37 /app/vendor/yiisoft/middleware-dispatcher/src/MiddlewareDispatcher.php(40): Yiisoft\Middleware\Dispatcher\MiddlewareStack->handle(Object(HttpSoft\Message\ServerRequest))
#38 /app/vendor/yiisoft/router/src/MatchingResult.php(81): Yiisoft\Middleware\Dispatcher\MiddlewareDispatcher->dispatch(Object(HttpSoft\Message\ServerRequest), Object(App\NotFoundHandler))
#39 /app/vendor/yiisoft/router/src/Middleware/Router.php(46): Yiisoft\Router\MatchingResult->process(Object(HttpSoft\Message\ServerRequest), Object(App\NotFoundHandler))
#40 /app/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(88): Yiisoft\Router\Middleware\Router->process(Object(HttpSoft\Message\ServerRequest), Object(App\NotFoundHandler))
#41 /app/vendor/yiisoft/yii-web/src/Middleware/SubFolder.php(75): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#42 /app/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(88): Yiisoft\Yii\Web\Middleware\SubFolder->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#43 /app/vendor/yiisoft/error-handler/src/Middleware/ErrorCatcher.php(135): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#44 /app/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(88): Yiisoft\ErrorHandler\Middleware\ErrorCatcher->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#45 /app/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(53): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#46 /app/vendor/yiisoft/middleware-dispatcher/src/MiddlewareDispatcher.php(40): Yiisoft\Middleware\Dispatcher\MiddlewareStack->handle(Object(HttpSoft\Message\ServerRequest))
#47 /app/vendor/yiisoft/yii-web/src/Application.php(57): Yiisoft\Middleware\Dispatcher\MiddlewareDispatcher->dispatch(Object(HttpSoft\Message\ServerRequest), Object(App\NotFoundHandler))
#48 /app/src/ApplicationRunner.php(75): Yiisoft\Yii\Web\Application->handle(Object(HttpSoft\Message\ServerRequest))
#49 /app/public/index.php(26): App\ApplicationRunner->run()
#50 {main}
```

### Additional info

| Q                | A
| ---------------- | ---
| Version          | yii3
| PHP version      |  8.0.3
| Operating system | ubuntu

**Comment by devanych** [comment]
Fixed. @tarunjangra thanks.
